---                                                                                                                                               
- name: print out astro data from vars file                                                                                                
  hosts: localhost                                                                                                                       
  connection: local                                                                                                                  
                                                                                                                      
  vars_files:                                                                                                                     
          - vars/astros2.yml                                                                                        
                                                                                                               
  tasks:                                                                                           
          - name: print out Jessic Meir                                                                    
            debug:                                                                                            
                    msg: "{{ astros.people[4].name }}"        
                                                                                                 
          - name: print out ALL astros                                                  
            debug:                                                                     
                    msg: "{{ item.name }}"                                          
            loop: "{{ astros.people }}"                                         
                                                                         
          - name: print out number of astros on ISS            
            debug:                                                      
                    msg: "{{ astros.number }}"
