---

- name: Learning to Recalling var data
  hosts: localhost
  connection: local


  vars:
    telecom:
        - ericsson
        - alu
        - avaya
        - cisco
    heroes:
            marvel:
                    - spiderman
                    - ironman
                    - daredevil

            dc: 
                    - wonderwoman
                    - batman
                    - superman

  tasks:
    - name: Print out spiderman
      debug: 
        msg: "{{ heroes.marvel[0] }}"

    - name: Print out batman
      debug: 
        msg: "{{ heroes.dc[1] }}"

    - name: Print out ALL DC heroes
      debug: 
        msg: "{{ heroes.dc }}"

    - name: Print out cisco
      debug: 
        msg: "{{ telecom[3] }}"


    - name: Print out ALL DC heroes
      debug:
        msg: "{{ heroes.dc + heroes.marvel}}"
